export const ADD_GOOD='ADD_GOOD';
export const DELETE_GOOD='DELETE_GOOD';
export const DELETE_ALL='DELETE_ALL';
export const SHOW_DELETE_ALL_BUTTON='SHOW_DELETE_ALL_BUTTON';
export const HIDE_DELETE_ALL_BUTTON='HIDE_DELETE_ALL_BUTTON';